# Generated by Django 3.1.7 on 2021-05-25 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0002_auto_20210525_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oxygen',
            old_name='AgencyAddress',
            new_name='agencyaddress',
        ),
        migrations.RenameField(
            model_name='oxygen',
            old_name='Agencyname',
            new_name='agencyname',
        ),
        migrations.RenameField(
            model_name='oxygen',
            old_name='Agencyphonenumber',
            new_name='agencyphone',
        ),
        migrations.RenameField(
            model_name='oxygen',
            old_name='name',
            new_name='leadname',
        ),
        migrations.RenameField(
            model_name='oxygen',
            old_name='verification',
            new_name='verified',
        ),
    ]
